Waas best practices
0xsequence/docs-v2 pull request #109
Opened 2024-05-03 14:55 UTC by moskalyk

2024-05-05 21:00 UTC, ScreamingHawk commented on docs/pages/solutions/wallets/embedded-wallet/best-practices.mdx
> +When complete with testing, make sure to remove any localhost origins so others do not also do gain local access to your Embbedded Wallet environment.
typo Embedded -> Embedded in a few places.

2024-05-05 21:00 UTC, ScreamingHawk commented on docs/pages/solutions/wallets/embedded-wallet/best-practices.mdx
> +Ensure not to publish your WaaS Config Key anywhere online (e.g. github), so that your Embedded Wallet instance is not used by someone not yourself, as allowed origins do not apply to mobile games be
If `WaasConfigKey` needs to be secret, should it also remain out of distributed client applications? e.g. exes and webpages. Only used by the application server.

2024-05-05 21:00 UTC, ScreamingHawk commented on docs/pages/solutions/wallets/embedded-wallet/best-practices.mdx
> +When accessing alchemical thermodynamic energies for various games, ensuring to construct complimentary and adjusting practices of information or affordance can help maintain healthy ownership. As an
`alchemical thermodynamic energies` too abstract?

2024-05-05 21:00 UTC, ScreamingHawk commented on docs/pages/solutions/wallets/embedded-wallet/best-practices.mdx
> +Making multiple transactions by accident can also be prevented by implementing the use of a local mutex to hold state until a transaction is complete, only then making UI changes.
Also consider batching transactions when multiple transactions are expected.

2024-05-10 13:04 UTC, JamesLawton requested changes

2024-05-10 13:04 UTC, JamesLawton commented on docs/pages/solutions/wallets/embedded-wallet/best-practices.mdx
> +When accessing alchemical thermodynamic energies for various games, ensuring to construct complimentary and adjusting practices of information or affordance can help maintain healthy ownership. As an
Typo in 'embbedded' wallet.

I don't understand this section. What is the goal here and what are we trying to communicate?

2024-05-10 13:04 UTC, JamesLawton commented on docs/pages/solutions/wallets/embedded-wallet/best-practices.mdx
> +#### Internal Testing: Walk the Talk
This also needs further clarification as I'm not sure what we are trying to convey.

2024-05-10 13:04 UTC, JamesLawton commented on docs/pages/solutions/wallets/embedded-wallet/best-practices.mdx
> +With developers implementing an Embedded Wallet experience for their users that have the goal to create a minting function using a contract, developers have the options to either: (1) offer sponsored
Developers could also make a paid mint - I don't think these are the only options. I also suggest removing 'cloudflare' as there are other alternatives to doing a serverless mint (even though we have a guide covering that one specifically)

2024-05-21 17:17 UTC, moskalyk commented on docs/pages/solutions/wallets/embedded-wallet/best-practices.mdx
> +Making multiple transactions by accident can also be prevented by implementing the use of a local mutex to hold state until a transaction is complete, only then making UI changes.
you can't batch transact with embedded wallet, as far as im aware. if so, we need to update our docs

2024-05-21 17:20 UTC, moskalyk commented on docs/pages/solutions/wallets/embedded-wallet/best-practices.mdx
> +Ensure not to publish your WaaS Config Key anywhere online (e.g. github), so that your Embedded Wallet instance is not used by someone not yourself, as allowed origins do not apply to mobile games be
What do you mean by application server? waas config lives in the frontend

2024-05-21 17:22 UTC, moskalyk commented on docs/pages/solutions/wallets/embedded-wallet/best-practices.mdx
> +When accessing alchemical thermodynamic energies for various games, ensuring to construct complimentary and adjusting practices of information or affordance can help maintain healthy ownership. As an
it feels like embedded wallets get you closer to the technology, but there are side effects that might need adjusting through things like marketing or additional interaction that a game studio should think about

i updated this to 
> When accessing possibilities of experience for various games

2024-05-21 17:22 UTC, moskalyk commented on docs/pages/solutions/wallets/embedded-wallet/best-practices.mdx
> +#### Internal Testing: Walk the Talk
updated to 

> #### Internal Testing: Practicing your values

2024-05-21 19:16 UTC, ScreamingHawk commented on docs/pages/solutions/wallets/embedded-wallet/best-practices.mdx
> +Ensure not to publish your WaaS Config Key anywhere online (e.g. github), so that your Embedded Wallet instance is not used by someone not yourself, as allowed origins do not apply to mobile games be
If it's client side it's insecure and you should assume it's public knowledge. No reason to hide config from github. 
If it shouldn't be public, it shouldn't be client side.

2024-07-10 10:29 UTC, closed without merging