Embedded parent wallet section addition
0xsequence/docs-v2 pull request #124
Opened 2024-05-17 17:53 UTC by moskalyk

2024-05-17 20:06 UTC, taylanpince requested changes

2024-05-17 20:06 UTC, taylanpince commented on docs/pages/solutions/builder/embedded-wallet/parent-wallet.mdx
> +# Embedded Wallet Parent Wallet
I think we can remove this page @moskalyk What do you think? You've covered the same info on the main overview page.

2024-05-17 20:06 UTC, taylanpince commented on docs/pages/solutions/builder/embedded-wallet/index.mdx
>  To make modifications to your Embedded Wallet configuration, navigate to the Embedded Wallet section again and make the necessary changes. Then click "Save Configuration" and enter your update code t
Can you also change this to reflect that we now call this "password" and not "update code". And also how important it is to store the password securely? If the password is lost we can't help them update their configuration.

2024-05-24 13:18 UTC, moskalyk commented on docs/pages/solutions/builder/embedded-wallet/parent-wallet.mdx
> +# Embedded Wallet Parent Wallet
sounds good

2024-05-24 13:19 UTC, moskalyk commented on docs/pages/solutions/builder/embedded-wallet/index.mdx
>  To make modifications to your Embedded Wallet configuration, navigate to the Embedded Wallet section again and make the necessary changes. Then click "Save Configuration" and enter your update code t
Okay added back in

2024-05-24 13:43 UTC, taylanpince approved these changes

2024-05-24 13:43 UTC, merged