Sequence kit upgrades
0xsequence/docs-v2 pull request #321
Opened 2024-10-03 15:00 UTC by moskalyk

2024-10-03 17:09 UTC, JamesLawton requested changes
Looks good overall, please see changes and then we can merge.

2024-10-03 17:09 UTC, JamesLawton commented on docs/pages/solutions/wallets/sequence-kit/getting-started.mdx
> +For web3 interactions, wagmi exposes a set of React hooks that make it convenient for common functions like sending transactions. Please check out our [Embedded Wallet boilerplate with Sequence Kit](
This isn't the Boilerplate with kit, can we update with the correct link?

2024-10-03 17:09 UTC, JamesLawton commented on docs/pages/solutions/wallets/sequence-kit/getting-started.mdx
> +Next, a configuration variable for Sequence Kit will need to be created as either a `waas` (meaning an [Embedded Wallet](http://localhost:5173/solutions/wallets/embedded-wallet/overview)) or `univers
These links are both using localhost, please update with the proper links

2024-10-03 17:09 UTC, JamesLawton commented on docs/pages/solutions/wallets/sequence-kit/getting-started.mdx
> +In order to customize further, [you can view additional configuration parameters.](https://github.com/0xsequence/kit?tab=readme-ov-file#setting-up-the-library)
Let's add a page called **Custom Configuration** as another page instead of linking to github. Then we can add the example configuration along with the interface schema for createConfigOptions so users have the option to navigate to that page to get the full breadth of options.

2024-10-04 15:24 UTC, moskalyk commented on docs/pages/solutions/wallets/sequence-kit/getting-started.mdx
> +In order to customize further, [you can view additional configuration parameters.](https://github.com/0xsequence/kit?tab=readme-ov-file#setting-up-the-library)
I'm not sure I see the reason for providing the custom configuration? If with the easy approach you can encompass everything

2024-10-07 07:40 UTC, JamesLawton approved these changes

2024-10-07 07:40 UTC, merged